title: Terrain Website
description: >
  Making a procedural terrain look more visually appealing.
  
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://zackoon.github.io/" # the base hostname & protocol for your site, e.g. http://example.com

remote_theme: pages-themes/merlot@v0.2.0
plugins:
  - jekyll-remote-theme
  - jekyll-feed